("Primeiro e último nome de uma pessoa")
nome = input("Digite seu nome completo: ")
nome = nome.strip()
nome = nome.split()
print("O primeiro nome é: {}".format(nome[0]))
print("O último nome é: {}".format(nome[len(nome)-1]))